---
# tasks file for installing gradle

- include_tasks: "{{ ansible_os_family }}.yml"

- name: Download and unarchive gradle
  unarchive:
    src: "https://services.gradle.org/distributions/\
          gradle-{{ gradle_version }}-bin.zip"
    dest: "{{ gradle_install_dir }}"
    remote_src: yes

- name: Add gradle bin to PATH
  copy:
    dest: "/etc/profile.d/gradle-path.sh"
    content: "PATH=$PATH:{{ gradle_install_dir }}/\
              gradle-{{ gradle_version }}/bin"
    mode: 0744
